### ISSUE TITLE
Invalid Credentials!

### ISSUE THREAD

**Issue by danboh** [odonata95/laravel-angular-boilerplate#1]
Thank you for this boilerplate!

It seems to be working ok, except that when trying to register after entering all the values I get the error "invalid credentials". Is the functionality for logging and registration not implemented yet on this version?

Thanks

**Comment by odonata95** [comment]
Try to restart Wamp. And try again.

If this does not help, check that you follow the instructions below:
- You need to install PHP server (such as Wamp or Apache), Composer and nodeJS.
- Then add a virtual host which reference to your public folder 
(for example: name - boilerplate; folder - C:/Wamp/www/test/Server/public). 
- In client in environment file add this host url (for example apiUrl: 'http://boilerplate/api')
- Open phpmyadmin and create DB (for example: myDB).
- Then open .env file and add your DB credentials
(for example: DB_CONNECTION=mysql DB_HOST=127.0.0.1 DB_PORT=3306 DB_DATABASE=myDB DB_USERNAME=root)
- Go to Server folder and run: `composer install` 
- Then run: `npm i`
- Then run migration to update your DB to current version: `php artisan migrate`
- Change APP_KEY: `php artisan key:generate`
- Change JWT secret: `php artisan jwt:generate`
- Globally install Angular CLI using command: `npm install -g @angular/cli@latest`
- Open Client folder in terminal/console and run: `npm i`
- Run: `ng serve`
- Navigate to http://localhost:4200/

**Comment by danboh** [comment]
Thanks for the quick response and thorough response.

I realized that I was missing "api" at the end of the API url in the client environment configuration file. 

Thanks!!

**Comment by sajjadsaleem** [comment]
I tried all this but it is still not working, cross origin issue is coming
My angular front-end is at at  localhost:4200 and Server at localhost/api

**Comment by odonata95** [comment]
did you try to restart server ?

2018-05-14 14:17 GMT+03:00 sajjadsaleem <notifications@github.com>:

**Comment by sajjadsaleem** [comment]
yes.

**Comment by cryptotym** [comment]
Hi,

I was having the same issue and turns out it was because the new Wamp is slightly different.. You must enable the virtual env by following this video https://www.youtube.com/watch?v=h-itXgXFli0 (similarly since the directories have changed) then add these sections:
```
<VirtualHost *:80>
DocumentRoot "C:\projectfolder\Server\public"
    <Directory  C:\projectfolder\Server\public">
	Options +Indexes +FollowSymLinks +MultiViews
	AllowOverride All
	Require local
    </Directory>
</VirtualHost>
```
Cool thing about doing it this way is that you can work directly from the project folder instead of moving anything it to the www location.
