### ISSUE TITLE
How to point server/api/login from client in production build?

### ISSUE THREAD

**Issue by pppalanikumar** [odonata95/laravel-angular-boilerplate#3]
How to point server/api/login from a client in the production build

**Comment by odonata95** [comment]
Add your production URL to /Client/src/environments/environment.prod.ts

**Comment by pppalanikumar** [comment]
Created the virtual host
URL: lara-ang.local
This URL points Client/dist/
Now how can I access the Server API's?
I had added lara-ang.local in /Client/src/environments/environment.prod.ts. But it's not working. 
Kindly guide me how can I access.

**Comment by odonata95** [comment]
You need URL in environment.prod.ts (for production) and environment.ts (for development) like this
apiUrl: 'http://lara-ang.local/api'
Do you add your URL right?

**Comment by pppalanikumar** [comment]
Yes, I have added. 
This URL points Client/dist/
But it's not working.

**Comment by odonata95** [comment]
Do you understand that to run built client (when you use Laravel) you need it in `Server/public/` folder (but not in `Client/dist/`)?
